---
:run: true # mettre à true pour jouer les tests ci-dessous (sinon, à false)
:tests_on:
  - masset_creation
:tests_off:
  - checklist_from_modele
  - essai
  - creer_tableau
  - modele_de_checklist